# Generated by Django 5.1.6 on 2025-12-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_teacher_bio_teacher_email_teacher_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
