# Generated by Django 5.1.6 on 2026-01-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
